FROM ubuntu:16.04

LABEL maintainer="thuydt@greenglobal.vn"
RUN apt-get -qq update && apt-get install -qqy wget 
RUN apt-get install -qqy default-jre net-tools iputils-ping netcat telnet curl dnsutils nano
WORKDIR /app

